language: python
dist: xenial
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip setuptools wheel black pytest-black
  - pip install --upgrade jaxlib==0.1.55 jax==0.2.0
  - pip install -r requirements.txt
script:
  - pip install -e .
  - black rljax --check
  - pytest --black -m "not (slow or mujoco)" tests